name: CI/CD Pipeline with DevSecOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run Gitleaks to check for sensitive information
      - name: Run Gitleaks to check for sensitive information
        uses: gitleaks/gitleaks-action@v2

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Set environment variables
      - name: Set environment variables
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/hello-world"
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}

      # Step 7: Push Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ${{ env.IMAGE_NAME }}

      # Step 8: Scan Docker image for vulnerabilities with Trivy
      - name: Scan Docker image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
