name: CI/CD Pipeline with DevSecOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Code scanning for secrets using Gitleaks
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Gitleaks to check for sensitive information
        uses: gitleaks/gitleaks-action@v2

  # Build Docker image and scan it with Trivy
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: secrets-scan
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.actor }}/hello-world:latest

      # Step 5: Push Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.actor }}/hello-world:latest

      # Step 6: Scan Docker image for vulnerabilities with Trivy
      - name: Scan Docker image for vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.actor }}/hello-world:latest
